Fix bug where players joining during Goliath match would get stuck in spectate
This is because respawning for such players would fail, due to the PLAYERS_RESPAWN event handler trying to delete repel zone that wasn't set up - the fix is to only assign a ship type to players joining between matches

Error in log was as follows:

  ERROR: Error while dispatching PLAYERS_RESPAWN
    TypeError: Cannot read property 'hitbox' of undefined
      at GamePlayersRespawn.onRespawnPlayer (dist/server/modes/base/maintenance/players/respawn.js:59:72)
      at EventEmitter.emit (node_modules/eventemitter3/index.js:182:35)
      at GameMatches.emit (dist/server/system.js:18:25)
      at dist/server/modes/btr/maintenance/matches.js:97:18
      at Map.forEach (<anonymous>)
      at GameMatches.prepareNewMatch (dist/server/modes/btr/maintenance/matches.js:86:33)
      at GameMatches.onSecondTick (dist/server/modes/btr/maintenance/matches.js:105:26)
      at EventEmitter.emit (node_modules/eventemitter3/index.js:203:33)
      at GameClock.emit (dist/server/system.js:18:25)
      at GameClock.onTick (dist/server/modes/base/maintenance/clock.js:55:22)